version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install tools
          command: apt install build-essential sqlite3
          
      - run:
          name: Build
          command: gcc -O2 -flto -o sqlite_sparse sqlite_sparse.c
